// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkCcI9xWyxcdyfuQHyorkrDvi9IB8_Xn4',
    appId: '1:156938940217:web:73301befe1a655b1c082e8',
    messagingSenderId: '156938940217',
    projectId: 'trendy-c-57ade',
    authDomain: 'trendy-c-57ade.firebaseapp.com',
    storageBucket: 'trendy-c-57ade.firebasestorage.app',
    measurementId: 'G-MQLLMN0F5P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx2DM2h3sFpd9VF8OcchIwG_eI12z9np4',
    appId: '1:156938940217:android:9f170f70ffbe3eb4c082e8',
    messagingSenderId: '156938940217',
    projectId: 'trendy-c-57ade',
    storageBucket: 'trendy-c-57ade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFWz9WLDKGO6F6-VWqBLhQ6ukZVIHh68M',
    appId: '1:156938940217:ios:4f39390a82ac9f2cc082e8',
    messagingSenderId: '156938940217',
    projectId: 'trendy-c-57ade',
    storageBucket: 'trendy-c-57ade.firebasestorage.app',
    androidClientId: '156938940217-3b5ph78k56n7iv16jcfm3th525ajvtn6.apps.googleusercontent.com',
    iosClientId: '156938940217-2op9d290letj42hcu203rlhrdsf6slkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.trendychef',
  );
}
